language: c
addons:
  apt:
    packages:
      # LaTeX
      - texlive-base

compiler:
  - gcc

script:
  - CFLAGS="-O2 -Wall --coverage -ftest-coverage -fprofile-arcs"  make -e dtl
  - make tests
  - make codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)
